# Generated by Django 6.0.3 on 2026-04-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_follow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
